openlibhums/typesetting

README.md, logic.py, templates/typesetting/elements/complete_typesetting.html, views.py
- Tweaks message on modal
- Fixes the complete process
- Adds readme info just for fun
=> Fix complete typesetting wording

templates/typesetting/elements/production_files.html, templates/typesetting/elements/sidebar.html, templates/typesetting/elements/transform_modal.html
=> Adds row hook for conversion plugins

models.py
=> Completing a task marks it as accepted.

migrations/0002_typesettinground.py, migrations/0006_auto_20200227_1051.py
submission 0042 and 0041 don't exist in master
=> Fix reference to missing migrations

templates/typesetting/elements/dashboard.html
=> Updated dashboard block.

views.py
=> 37 Fixed permission on proofreader list.

templates/typesetting/elements/typesetter/metadata.html
Most of these were already in place.
=> Closes #46

templates/typesetting/elements/actions.html, templates/typesetting/typesetting_review_assignment.html
=> 50 fixes action page logic and expands a row in typesetting review.

templates/typesetting/elements/typesetter/metadata.html, templates/typesetting/typesetting_assignments.html, templates/typesetting/typesetting_proofing_assignments.html, views.py
=> 49 completed task list

templates/typesetting/typesetting_article.html
=> #51 hide actions for all old rounds

templates/typesetting/elements/typesetter/agreement.html, templates/typesetting/elements/typesetter/info.html, templates/typesetting/typesetting_assignment.html
=> updates typesetting template.

templates/typesetting/elements/typesetter/agreement.html, templates/typesetting/elements/typesetter/info.html, templates/typesetting/typesetting_assignment.html
=> #55 updates typesetting template.

templates/typesetting/typesetting_manage_proofing_assignment.html
=> #62 Editing proofing assignment now uses jqte boxes.

templates/typesetting/elements/card.html
=> #65 Added article pks to kanban card titles

security.py, templates/typesetting/elements/proofing.html, templates/typesetting/elements/typesetter.html, views.py
=> #63 adds links to send unsent notifications

templates/typesetting/assign_typesetter.html, views.py
=> 67 assign typesetter now filters out uncompleted proofing tasks.

views.py
=> 66 Switched to plugin decorator.

templates/typesetting/elements/dashboard.html, templatetags/role_count.py
=> 64 adds counts to dashboard.

forms.py, logic.py, templates/typesetting/assign_typesetter.html, templates/typesetting/edit_galley.html, templates/typesetting/elements/add_new_round.html, templates/typesetting/elements/complete_typesetting.html, templates/typesetting/elements/galleys.html, templates/typesetting/elements/new_galley.html, templates/typesetting/elements/new_production_file.html, templates/typesetting/elements/no_typesetter.html, templates/typesetting/elements/production_files.html, templates/typesetting/elements/sidebar.html, templates/typesetting/elements/transform_modal.html, templates/typesetting/elements/typesetter/galleys.html, templates/typesetting/typesetting_article.html, templates/typesetting/typesetting_assign_proofreader.html, templates/typesetting/typesetting_assignment.html, templates/typesetting/typesetting_manage_proofing_assignment.html, templates/typesetting/typesetting_proofreading_assignment.html, templates/typesetting/typesetting_review_assignment.html, views.py
Closes #80 
Closes #81 
Closes #82
=> #80 changed the word Galley for Typeset files where applicable.

templates/typesetting/elements/transform_modal.html
=> Fixes wrong url in template for making galleys

install/settings.json
- Added subject settings
- Updated some pretty names to match newer converntion.
Closes #95
=> #95 added subject emails.

templates/typesetting/elements/typesetter.html
=> #85 changes made to text as recommended

templates/typesetting/elements/dashboard.html
=> #86 re-ordered the dashboard buttons.

templatetags/role_count.py
=> #98 fixes role counter for typesetter.

templates/typesetting/typesetting_review_assignment.html
=> 84 edit assignment

models.py, templates/typesetting/elements/proofing.html, templates/typesetting/elements/typesetter.html, templates/typesetting/typesetting_assignments.html, templates/typesetting/typesetting_proofing_assignments.html, views.py
=> #87 dates in ISO format and time hidden where not need.

templates/typesetting/typesetting_manage_proofing_assignment.html, templates/typesetting/typesetting_proofreading_assignment.html, views.py
=> proofing fixes

hooks.py, plugin_settings.py, templates/typesetting/elements/author_tasks.html
=> #91 Added hooks to display tasks on author page.

urls.py
=> support image paths without '/figure'

templates/typesetting/elements/typesetter/source_files.html, templates/typesetting/typesetting_article.html, templates/typesetting/typesetting_assignment.html, views.py
=> Source files

templates/typesetting/assign_typesetter.html, templates/typesetting/notify_typesetter.html, templates/typesetting/typesetting_article.html, templates/typesetting/typesetting_assign_proofreader.html, templates/typesetting/typesetting_assignment.html, templates/typesetting/typesetting_manage_proofing_assignment.html, templates/typesetting/typesetting_notify_proofreader.html, templates/typesetting/typesetting_review_assignment.html
Part of birkbeckctp/janeway#2203
=> Updated template sub titles to new format.

forms.py, templates/typesetting/edit_galley.html, templates/typesetting/elements/galleys.html, templates/typesetting/elements/new_galley.html, views.py
Tied to https://github.com/BirkbeckCTP/janeway/pull/2479
=> Allows typeset files to marked as not for public

security.py
=> Fixes redirects after asking to login not working properly on path mode journals

forms.py, templates/typesetting/elements/author_tasks.html, templates/typesetting/typesetting_proofreading_assignment.html, views.py
Part of https://github.com/BirkbeckCTP/janeway/issues/2753 .
=> Add confirmation modal to proofreader assignment

forms.py, templates/typesetting/assign_typesetter.html, templates/typesetting/typesetting_assign_proofreader.html, views.py
Part of BirkbeckCTP/janeway#2822.
=> Warn production editors of inactive typesetter and proofreader / author accounts

templates/typesetting/edit_galley.html, templates/typesetting/elements/file_list.html, templates/typesetting/elements/galleys.html, templates/typesetting/elements/production_files.html, templates/typesetting/elements/supplementary_files.html, templates/typesetting/elements/typesetter/galleys.html, templates/typesetting/elements/typesetter/source_files.html
=> #158 swaps date_modified for last_modified

models.py, templates/typesetting/notify_typesetter.html, templates/typesetting/typesetting_notify_proofreader.html, tests.py, views.py
Part of https://github.com/BirkbeckCTP/janeway/issues/2737
=> #2737 adds support for the core Archived stage.

plugin_settings.py
Bumps version to 1.2 and marks this version as compatible with 1.4.3
=> Bump version and compatible version

templates/typesetting/elements/supp_file_label.html, templates/typesetting/elements/supplementary_files.html, templates/typesetting/typesetting_article.html, views.py
Allows editors to make changes to the labels on support files
=> Edit supp labels

templates/typesetting/assign_typesetter.html, templates/typesetting/elements/typesetter/metadata.html
Completes BirkbeckCTP/janeway#2750
Completes #171
=> Catch all assigned issues rather than relying on primary_issue

views.py
Related to birkbeckCTP/janeway#3979
=> Janeway warns if you try to upload a galley image with a duplicate filename

templates/typesetting/elements/typesetter/files.html, templates/typesetting/typesetting_assignment.html
=> Typesetters can see date that files were last modified

logic.py, templates/typesetting/crossref/crossref_component.xml
- Part of birkbeckctp/janeway#3486
=> birkbeckctp/janeway#3486 component DOI minting now using the same timestamp format as core.

plugin_settings.py, views.py
same as https://github.com/BirkbeckCTP/janeway/pull/4147 but for typesetting plugin
=> Fixed an issue where galleys generated throug transformation where getting their metrics recorded

install/settings.json, migrations/0015_article_title_safe.py, templates/typesetting/assign_typesetter.html, templates/typesetting/elements/title_sub.html, templates/typesetting/notify_typesetter.html, templates/typesetting/typesetting_article.html, templates/typesetting/typesetting_articles.html, templates/typesetting/typesetting_assign_proofreader.html, templates/typesetting/typesetting_assignment.html, templates/typesetting/typesetting_manage_proofing_assignment.html, templates/typesetting/typesetting_notify_proofreader.html, templates/typesetting/typesetting_review_assignment.html
This completes a few cleanup tasks related to BirkbeckCTP/janeway#4258 and BirkbeckCTP/janeway#4267.
=> Update setting types and article title rendering

migrations/0017_auto_20240708_1727.py, models.py, templates/typesetting/assign_typesetter.html, templates/typesetting/elements/typesetter/galleys.html, templates/typesetting/elements/typesetter/info.html, templates/typesetting/elements/typesetting_assignment_fields.html, templates/typesetting/typesetting_assignment.html
=> Integrate typesetting guide into assignment cycle
